# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"q\n\x0fRegisterRequest\x12\x16\n\x0e\x65mail_or_phone\x18\x01 \x01(\t\x12\x0b\n\x03otp\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x15\n\ruse_biometric\x18\x05 \x01(\x08\"O\n\x0cLoginRequest\x12\x16\n\x0e\x65mail_or_phone\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x15\n\ruse_biometric\x18\x03 \x01(\x08\"B\n\x0c\x41uthResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t2a\n\x0bUserService\x12+\n\x08Register\x12\x10.RegisterRequest\x1a\r.AuthResponse\x12%\n\x05Login\x12\r.LoginRequest\x1a\r.AuthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=14
  _globals['_REGISTERREQUEST']._serialized_end=127
  _globals['_LOGINREQUEST']._serialized_start=129
  _globals['_LOGINREQUEST']._serialized_end=208
  _globals['_AUTHRESPONSE']._serialized_start=210
  _globals['_AUTHRESPONSE']._serialized_end=276
  _globals['_USERSERVICE']._serialized_start=278
  _globals['_USERSERVICE']._serialized_end=375
# @@protoc_insertion_point(module_scope)
